version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"    # Пробрасываем порт 3000 из контейнера на локальную машину
    volumes:
      - .:/app          # Пробрасываем текущий каталог в контейнер для автоперезагрузки
      - /app/node_modules  # Исключаем node_modules из проброса, чтобы использовать контейнерные зависимости
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
