version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: FastAPI
      POSTGRES_USER: FastAPI_user
      POSTGRES_PASSWORD: Plotar1404
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: ./backend  # Путь до Dockerfile с FastAPI
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://FastAPI_user:Plotar1404@db/FastAPI
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend  # Путь до Dockerfile с React
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
