version: '3.8'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Transcription_Project
    depends_on:
      - postgres
      - minio
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: "postgresql://postgres:Plotar1404@postgres:5432/Transcription"
      MINIO_URL: "http://minio:9000"
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Plotar1404
      POSTGRES_DB: Transcription
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: "Root123"
      MINIO_ROOT_PASSWORD: "Root123312213n"
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    networks:
      - app_network

  react-app:
    build:
      context: ./frontend  # Путь к директории с React приложением
      dockerfile: Dockerfile  # Dockerfile для React
#    container_name: frontend
    ports:
      - "3000:80"  # Порт для React
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
